version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: communal
    volumes:
      - communal_pg:/var/lib/postgresql/data
volumes:
  communal_pg:
      external: true